# Generated by Django 1.11.5 on 2017-12-22 16:14


from typing import ClassVar

from django.db import migrations


class Migration(migrations.Migration):
    dependencies: ClassVar = [
        ("programmes", "0013_programme_website"),
    ]

    operations: ClassVar = [
        migrations.AlterUniqueTogether(
            name="episode",
            unique_together={},
        ),
    ]
