# Generated by Django 1.11.5 on 2017-12-25 22:35

from typing import ClassVar

from django.db import migrations


class Migration(migrations.Migration):
    dependencies: ClassVar = [
        ("programmes", "0015_remove_programme_runtime"),
    ]

    operations: ClassVar = [
        migrations.AlterUniqueTogether(
            name="episode",
            unique_together={("season", "number_in_season", "programme")},
        ),
    ]
