[project]
name = "radioco"
version = "0.1.0"
description = "This app provides an easy way to set up your radio"
readme = "README.md"
authors = [
    { name = "Iago Veloso Abalo", email = "author@radioco.org" },
    { name = "Stefan Walluhn", email = "stefan@walluhn.de" }
]
license="GPL-3.0-only"
requires-python = ">=3.13"
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Environment :: Web Environment",
    "Framework :: Django",
    "Intended Audience :: Developers",
    "Intended Audience :: End Users/Desktop",
    "Operating System :: OS Independent",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
    "Topic :: Internet :: WWW/HTTP",
    "Topic :: Internet :: WWW/HTTP :: Dynamic Content",
]
dependencies = [
    "django>=6.1.1",
    "django-ckeditor>=6.7.3",
    "django-filebrowser>=5.0.0",
    "django-filter>=26.1",
    "django-grappelli>=4.0.4",
    "django-npm>=1.0.1",
    "django-recurrence>=1.14",
    "djangorestframework>=3.18.1",
    "whitenoise>=6.12.0",
]

[project.urls]
Repository = "https://github.com/RadioCorax/radioco"

[project.scripts]
radioco_admin = "radioco.cli:radioco_admin"
tests = "radioco.test.runner:runtests"

[build-system]
requires = ["uv_build>=0.12.17,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = []

[tool.ruff.lint]
ignore = ["DTZ001"]


[tool.pyright]
typeCheckingMode = "off"
