# Generated by Django 1.11.5 on 2017-12-21 15:13

from typing import ClassVar

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies: ClassVar = [
        ("schedules", "0005_auto_20170531_1001"),
    ]

    operations: ClassVar = [
        migrations.AlterField(
            model_name="schedule",
            name="type",
            field=models.CharField(
                choices=[
                    (b"L", "live"),
                    (b"B", "broadcast"),
                    (b"S", "broadcast syndication"),
                    (b"R", "repetition"),
                ],
                max_length=1,
                verbose_name="type",
            ),
        ),
    ]
