# Generated by Django 2.2.28 on 2023-01-30 19:15

from typing import ClassVar

from django.db import migrations

import radioco.schedules.wrapper


class Migration(migrations.Migration):
    dependencies: ClassVar = [
        ("schedules", "0008_auto_20180317_2251"),
    ]

    operations: ClassVar = [
        migrations.AlterField(
            model_name="schedule",
            name="recurrences",
            field=radioco.schedules.wrapper.RecurrenceFieldWrapper(
                verbose_name="recurrences"
            ),
        ),
    ]
